### ISSUE TITLE
can you add it in docker hub?

### ISSUE THREAD

**Issue by Crosus97** [TeaSpeak/TeaDocker#6]
"insert title"

**Comment by WolverinDEV** [comment]
Which one exactly?

**Comment by Crosus97** [comment]
Server Ubuntu or debian what you want

**Comment by WolverinDEV** [comment]
Yes, but the WebBuild, TeaSpeak server etc?
And why?

**Comment by Crosus97** [comment]
> Yes, but the WebBuild, TeaSpeak server etc?

Server

> And why?

I dont really good with Docker and DockerHub with Kitematic is 1 Click install
and i think is easy to creator of docker to upload to DockerHub

If you can't do it or is to difficult, no problem, but I'd be very grateful if you could do it.

**Comment by WolverinDEV** [comment]
Hey,
I totally forgot about it.
But as you see in this pr https://github.com/TeaSpeak/TeaDocker/pull/7 its getting forwards.
So I guess in a few days TeaSpeak will be available on docker hub.
